apiVersion: v1
kind: Service
metadata:
  name: ollama-exporter
  namespace: llm
  labels:
    app: ollama-exporter
    part-of: llm-observability-stack
spec:
  ports:
  - port: 9099
    targetPort: metrics
    name: metrics
  - port: 11435
    targetPort: proxy
    name: proxy
  selector:
    app: ollama-exporter
